### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by spkesDE** [spkesDE/TelegramNotifications#2]
Needed Translation

- [x] DE
- [x] IT
- [x] NL
- [x] EN translation check

**Comment by spkesDE** [comment]
@ilpaolino well looks like it I'm done. It was easier the I though :) 
New files
- locales/it.json
- .homeycompose/flow/actions/send-a-question.json
- .homeycompose/flow/triggers/receive-question-answer.json
- .homeycompose/flow/triggers/receive-question-answer-with-answer.json

**Comment by ilpaolino** [comment]
Done, PR 4
https://github.com/spkesDE/TelegramNotifications/pull/4
