### ISSUE TITLE
Unable to edit recorded questions 

### ISSUE THREAD

**Issue by pippo73** [spkesDE/TelegramNotifications#7]
Entering the configuration of the app, I try to edit a question I've recorded with some answers. But nothing happens. If I press the delete button the question is deleted.

Anyway I can control why?

**Comment by spkesDE** [comment]
Looks like the feature is broken right now. I'll take a look at it and fix it asap

**Comment by spkesDE** [comment]
Edit mode is fixed. Update is live. You app will update automatically on your homey within the next hours or you can manually trigger a update

**Comment by pippo73** [comment]
WOW... this is realtime customer service! thanks a lot!
